runtime: python39
entrypoint: gunicorn -b :$PORT app:app
runtime: python39  # Đảm bảo bạn đang sử dụng Python 3

entrypoint: gunicorn -b :$PORT run:app  # Sử dụng gunicorn để chạy ứng dụng

env_variables:
  FLASK_ENV: "production"  # Bạn có thể thay đổi nếu cần

handlers:
  - url: /static
    static_dir: static/

  - url: /.*  # Điều này định tuyến tất cả các yêu cầu đến Flask app
    script: auto
