"""Add sold_quantity and rating to Product

Revision ID: 548b80ad181c
Revises: 948b90cddd00
Create Date: 2025-01-16 14:45:24.607803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548b80ad181c'
down_revision = '948b90cddd00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('sold_quantity')

    # ### end Alembic commands ###
